### PR TITLE
Fix #31

### LINKED ISSUE #31: Cursor is a missing glyph when inputting command in windows terminal
cursor

### LINKED ISSUE #37: run NTop on remote computer
I remember , I can run ntop on remote computer when I remote to a computer with powershell. I think it was in 2019,
But I find I can not do that now.
Is there anything change that cause fail to run it remotely ,any advise ?

### PR DESCRIPTION
**Pull request by dd86k**

### CODE REVIEW

**Comment by dd86k** [comment]
#37? No I meant #31 

I'm tired.

**Comment by gsass1** [comment]
But that would remove the caret completely though. Isn't there an ASCII code or some character that will work on all fonts?

**Comment by dd86k** [comment]
Something similar would be printing a space with inverted colors with `COMMON_LVB_REVERSE_VIDEO` instead of trying to find the block character in every code pages available. I could do that.

**Comment by gsass1** [comment]
That would be grand

**Comment by dd86k** [comment]
At least now the `_` caret is not in the extended ascii code and should be playing safe with other fonts. Tried to change the background of the character cell but to no avail -- the code structure is not that well put up.

**Pull request merged**
